name: CI

on:
    - pull_request
    - push

env:
    COMPOSER_ROOT_VERSION: '10.1-dev'

permissions:
    contents: read

jobs:
    end-to-end-tests:
        name: End-to-End Tests

        runs-on: ${{ matrix.os }}

        env:
            PHP_EXTENSIONS: none, curl, dom, json, libxml, mbstring, openssl, phar, soap, tokenizer, xml, xmlwriter, sockets, posix
            PHP_INI_VALUES: assert.exception=1, zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On

        continue-on-error: ${{ matrix.experimental }}

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest

                php-version:
                    - '8.1'
                    - '8.2'

                experimental:
                    - false

                include:
                    - os: ubuntu-latest
                      php-version: '8.3'
                      experimental: true

                    - os: windows-latest
                      php-version: '8.3'
                      experimental: true

        steps:
            - name: Configure Git to avoid issues with line endings
              if: matrix.os == 'windows-latest'
              run: git config --global core.autocrlf false

            - name: Checkout
              uses: actions/checkout@v4

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: ${{ env.PHP_EXTENSIONS }}
                  ini-values: ${{ env.PHP_INI_VALUES }}
                  coverage: none
                  tools: composer:v2

            - name: Install dependencies with Composer
              run: composer update --no-ansi --no-interaction --no-progress

            - name: Run tests with PHPUnit
              run: ./vendor/bin/phpunit --testsuite end-to-end
